# try:
#     # Код, который может вызвать исключение
#     result = 10 / 0  # Деление на ноль вызывает исключение
# except ZeroDivisionError:
#     # Код, который выполнится в случае исключения ZeroDivisionError
#     print("Ошибка: Деление на ноль!")
# else:
#     # Код, который выполнится, если исключение не возникло
#     print("Результат:", result)
# finally:
#     # Код, который выполнится всегда, независимо от того, было ли исключение или нет
#     print("Конец блока try-except")




# try:
#     print(c)
# except NameError:
#     print('Бул ошибка') 


# def func():
#     def inner():
#         print('Салам мен ички функциямын!')
#     inner()

# func()

# @fucn2
# def func():
#     print('Салам')


# def fucn2():
#     def inner():
#         print('кандайсын?')
#     return inner

# fucn2()